[versions]
google-gson = "2.13.2"
google-guava = "33.5.0-jre"
dnsjava-dnsjava = "3.6.4"
bungeecord-api = "1.21-R0.4"

[libraries]
google-gson-lib = { module = "com.google.code.gson:gson", version.ref = "google-gson" }
google-guava-lib = { module = "com.google.guava:guava", version.ref = "google-guava" }
dnsjava-lib = { module = "dnsjava:dnsjava", version.ref = "dnsjava-dnsjava" }
bungeecord-api-lib = { module = "net.md-5:bungeecord-api", version.ref = "bungeecord-api" }

[plugins]
freefair-lombok-plugin = { id = "io.freefair.lombok", version = "9.2.0" }
shadow-plugin = { id = "com.gradleup.shadow", version = "9.3.1" }